### ISSUE TITLE
Documentation's Cargo.toml: "Virtual manifests do not specify [dependencies]"

### ISSUE THREAD

**Issue by xobs** [rust-embedded/svd2rust#387]
It looks like the documentation instructs users to create something called a "Virtual manifest" by omitting the `[package]` directive at https://docs.rs/svd2rust/0.16.1/svd2rust/#target--cortex-m-1

```toml
[dependencies]
bare-metal = "0.1.0"
msp430 = "0.1.0"
vcell = "0.1.0"

[dependencies.msp430-rt]
optional = true
version = "0.1.0"

[features]
rt = ["msp430-rt"]
```

However, when using `rustc 1.37.0`, this Cargo.toml file does not work:

```powershell
> cargo check
error: failed to parse manifest at `D:\Code\xoulon-mcu\sw\xoulon-hal\Cargo.toml`

Caused by:
  virtual manifests do not specify [dependencies]
>
```
