### ISSUE TITLE
Hide peripherals under a feature gate each one.

### ISSUE THREAD

**Issue by jeandudey** [rust-embedded/svd2rust#433]
Compiling a complete crate generated using `svd2rust` results in a big compilation time (at least for my machine), mainly because of all the code that needs to be compiled. Adding a feature gate to each peripherals results in better compilation times.

For example one would use a Peripheral Access Crate like this by specifying the features on demand:

```toml
[dependencies.mymcu-pac]
version = "0.1"
features = ["uart", "gpio"]
```

A flag to `svd2rust` could be added to generate code with features on peripherals like `--use-features` (bad name, but gets the point) so I doesn't break existing code and is enabled explicitly.
