### ISSUE TITLE
Output Cargo.toml dependencies and features

### ISSUE THREAD

**Issue by Emilgardis** [rust-embedded/svd2rust#780]
Should we have a way to make `svd2rust` output a `[dependencies]` and `[features]` given a set of arguments?

```
svd2rust cargo-toml --impl-defmt defmt -i STM32F30x.svd
```

would give

```toml
[dependencies]
critical-section = { version = "1.0", optional = true }
cortex-m = "0.7"
cortex-m-rt = { version = "0.7", optional = true }
vcell = "0.1"
defmt = { version = "0.3", optional = true }


[features]
rt = ["cortex-m-rt/device"]
defmt = ["dep:defmt"]
```
